//MUTATIONS
export const SET_OPEN_LOGIN_PAGE = 'store/SET_OPEN_LOGIN_PAGE';
export const SET_OPEN_REGISTER_PAGE = 'store/SET_OPEN_REGISTER_PAGE';
export const SET_BROWSE_RESTAURANTS = 'store/SET_BROWSE_RESTAURANTS';
export const SET_OPEN_PROFILE_PAGE = 'store/SET_OPEN_PROFILE_PAGE';




// ACTIONS
export const ACTION_SET_OPEN_LOGIN_PAGE = 'store/ACTION_SET_OPEN_LOGIN_PAGE';
export const ACTION_SET_OPEN_REGISTER_PAGE = 'store/ACTION_SET_OPEN_REGISTER_PAGE';
export const ACTION_SET_BROWSE_RESTAURANTS = 'store/ACTION_SET_BROWSE_RESTAURANTS';
export const ACTION_SET_OPEN_PROFILE_PAGE = 'store/ACTION_SET_OPEN_PROFILE_PAGE';



